### PR TITLE
Tweak throttle wording

### PR DESCRIPTION
**Pull request by xavi-**

### CODE REVIEW

**Comment by nathanleiby** [comment]
My impression from the explosion of OOM messages in #oncall-infra is that we could throttle more aggressively -- do we want to do that here, too?

**Comment by xavi-** [comment]
The throttling change hadn't been deployed to prod yet.  I wanted to test in dev for a while.  I ended up deploying the change around 10:45~ yesterday.  The throttling seemed to work soon after.

It's probably worth moving the threshold into ark-config though.

**Comment by xavi-** [comment]
Will do that in a separate PR

**Comment by xavi-** [comment]
https://github.com/Clever/kinesis-notifications-consumer/pull/21

**Pull request merged**
